server:
  port: 9080

spring:
  application:
    name: producer-service
  cloud:
    function:
      definition: news
    stream:
      poller:
        fixed-delay: 5000
      bindings:
        news-out-0:
          destination: country/city/berlin
          binder: local-solace
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: admin
                clientPassword: admin
                connectRetries: -1
                reconnectRetries: -1

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always